# ░░░░░░░░░░░░░░░   HotkeyPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/HotkeyPlus.85995/
#  Wiki: https://github.com/momoservertw/HotkeyPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 2
Debugging: false
Check-Updates: true

Hotkey:
  Enable: false
  Settings:
    Help:
      Enable: true
      Command: "actionbar: &eHold the shift and click the hotkey \"f\" and \"0~8\"."
    Cooldown:
      Enable: true
      Interval: 2
      Message: false
  Groups:
    Shift-F:
      Enable: false
      PlaceHolder: "Menu"
      Commands:
        - "console: say %player% execute hotkey command - Shift-F"
    Shift-1:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-2:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-3:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-4:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-5:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-6:
      Enable: false
      PlaceHolder: ""
      Commands: []
    Shift-7:
      Enable: false
      PlaceHolder: ""
      Commands: []