name: HotkeyPlus
main: tw.momocraft.hotkeyplus.HotkeyPlus
author: Momocraft
api-version: 1.13
version: 1.0.0
description: To add cool hotkeys in your server.
depend: [ CorePlus ]

commands:
  hotkeyplus:
    description: Displays main command menu.
    permission: hotkeyplus.use
    aliases: [ hkp ]
    usage: |
      /hotkeyplus

permissions:
  hotkeyplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      hotkeyplus.use: true
      hotkeyplus.command.*: true
      hotkeyplus.hotkey.*: true
  hotkeyplus.use:
    description: Allows use of basic commands.
    default: true
  hotkeyplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      hotkeyplus.command.reload: true
      hotkeyplus.command.version: true
  hotkeyplus.command.reload:
    description: Allows use of /hotkeyplus command reload.
    default: op
  hotkeyplus.command.version:
    description: Allows use of command /hotkeyplus version.
    default: op
  hotkeyplus.hotkey.*:
    description: Allows use all keyboard hotkey.
    default: op
    children:
      hotkeyplus.hotkey.keyboard.*: true
  hotkeyplus.hotkey.keyboard.*:
    description: Allows use all keyboard hotkey.
    default: op
    children:
      hotkeyplus.hotkey.keyboard.shiftf: true
      hotkeyplus.hotkey.keyboard.shift1: true
      hotkeyplus.hotkey.keyboard.shift2: true
      hotkeyplus.hotkey.keyboard.shift3: true
      hotkeyplus.hotkey.keyboard.shift4: true
      hotkeyplus.hotkey.keyboard.shift5: true
      hotkeyplus.hotkey.keyboard.shift6: true
      hotkeyplus.hotkey.keyboard.shift7: true
      hotkeyplus.hotkey.keyboard.shift8: true
      hotkeyplus.hotkey.keyboard.shift9: true
  hotkeyplus.hotkey.keyboard.shiftf:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift1:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift2:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift3:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift4:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift5:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift6:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.keyboard.shift7:
    description: Allows use keyboard hotkey.
    default: op
  HotkeyPlus.hotkey.keyboard.shift8:
    description: Allows use keyboard hotkey.
    default: op
  HotkeyPlus.hotkey.keyboard.shift9:
    description: Allows use keyboard hotkey.
    default: op