# ░░░░░░░░░░░░░░░   HotkeyPlus, By Momocraft♥   ░░░░░░░░░░░░░░░
#  Spigot: https://www.spigotmc.org/resources/HotkeyPlus.85995/
#  Wiki: https://github.com/momoservertw/HotkeyPlus/wiki
# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
Config-Version: 2
Check-Updates: true

# To add cool hotkeys in your server.
# More information: https://github.com/momoservertw/HotkeyPlus/wiki/Hotkey
HotKey:
  Enable: true
  Keyboard:
    Enable: true
    Settings:
      Cooldown:
        Enable: true
        Interval: 20
        Message: false
    Groups:
      ShiftF:
        Enable: true
        Slot: -1
        Cancel: true
        Commands:
          - "console: say command Shift + F"
      Shift1:
        Enable: true
        Slot: 0
        Cancel: true
        Commands:
          - "console: say command Shift + 1"
      Shift2:
        Enable: true
        Slot: 1
        Cancel: true
        Commands:
          - "console: say command Shift + 2"
      Shift3:
        Enable: true
        Slot: 2
        Cancel: true
        Commands:
          - "console: say command Shift + 3"
      Shift4:
        Enable: true
        Slot: 3
        Cancel: true
        Commands:
          - "console: say command Shift + 4"
      Shift5:
        Enable: true
        Slot: 4
        Cancel: true
        Commands:
          - "console: say command Shift + 5"
      Shift6:
        Enable: true
        Slot: 5
        Cancel: true
        Commands:
          - "console: say command Shift + 6"
      Shift7:
        Enable: true
        Slot: 6
        Cancel: true
        Commands:
          - "console: say command Shift + 7"
      Shift8:
        Enable: true
        Slot: 7
        Cancel: true
        Commands:
          - "console: say command Shift + 8"
      Shift9:
        Enable: true
        Slot: 8
        Cancel: true
        Commands:
          - "console: say command Shift + 9"

Message:
  prefix: "&f[&eHotkeyPlus&f] &r"
  Commands:
    title: "&8▩▩▩▩▩▩▩▩▩▩ &dHotkeyPlus &8▩▩▩▩▩▩▩▩▩▩"
    help: "&f/hotkeyplus help &8- &7This help menu."
    reload: "&f/hotkeyplus reload &8- &7Reloads config file."
    version: "&f/hotkeyplus version &8- &7Checks the plugin version and updates."