name: HotkeyPlus
main: tw.momocraft.hotkeyplus.HotkeyPlus
author: Momocraft
api-version: 1.13
version: 1.1.0
description: To add cool hotkeys in your server.
depend: [ CorePlus ]

commands:
  hotkeyplus:
    description: Displays main command menu.
    permission: hotkeyplus.use
    aliases: [ hkp ]
    usage: |
      /hotkeyplus

permissions:
  hotkeyplus.*:
    description: Allows use of all commands and feature.
    default: op
    children:
      hotkeyplus.use: true
      hotkeyplus.command.*: true
      hotkeyplus.hotkey.*: true
  hotkeyplus.use:
    description: Allows use of basic commands.
    default: true
  hotkeyplus.command.*:
    description: Allows use all commands.
    default: op
    children:
      hotkeyplus.command.reload: true
      hotkeyplus.command.version: true
  hotkeyplus.command.reload:
    description: Allows use of /hotkeyplus command reload.
    default: op
  hotkeyplus.command.version:
    description: Allows use of command /hotkeyplus version.
    default: op
  hotkeyplus.command.prompt:
    description: Allows use of command /hotkeyplus prompt.
    default: op
  hotkeyplus.hotkey.*:
    description: Allows use all keyboard hotkey.
    default: op
    children:
      hotkeyplus.hotkey.shift-f: true
      hotkeyplus.hotkey.shift-1: true
      hotkeyplus.hotkey.shift-2: true
      hotkeyplus.hotkey.shift-3: true
      hotkeyplus.hotkey.shift-4: true
      hotkeyplus.hotkey.shift-5: true
      hotkeyplus.hotkey.shift-6: true
      hotkeyplus.hotkey.shift-7: true
      hotkeyplus.hotkey.shift-8: true
  hotkeyplus.hotkey.shift-f:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-1:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-2:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-3:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-4:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-5:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-6:
    description: Allows use keyboard hotkey.
    default: op
  hotkeyplus.hotkey.shift-7:
    description: Allows use keyboard hotkey.
    default: op
  HotkeyPlus.hotkey.shift-8:
    description: Allows use keyboard hotkey.
    default: op